Desktop
chawkimbarki/My_Portfolio pull request #1
Opened 2023-01-21 02:34 UTC by chawkimbarki

# Made Changes :
- Made the website compatible with big screens with 1440px width or more
- added all necessary assets (pictures, shapes ...)
- styled according to the Figma design

2023-01-21 03:19 UTC, franclobo requested changes
Hi @chawkimbarki, 

# Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/213841366-ec36a4af-d5f4-4ffa-a84f-2c8561f08292.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 


## Required Changes ♻️
_Check the comments under the review._

- Remember that all main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo. The getting started section should contain the instructions for users or recruiters that allow using your portfolio, please 🙏🏽 complete this section for a professional README file.

![image](https://user-images.githubusercontent.com/58642949/213841271-1d1012b2-4597-455f-af79-285b72a820b8.png)
 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 03:19 UTC, franclobo commented on style.css
> +@media only screen and (min-width: 1440px) {
- [ ] I recommend changing the min-width to 768px instead of 1440px otherwise I can´t see 🙈 the changes in the normal size screen of my PC.

2023-01-21 03:19 UTC, franclobo commented on style.css
> +  }
- [ ] The paragraph and the button are left aligned, kindly fix it to be similar to the Figma template 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/213840922-bab339ff-6c86-4c55-91d1-f60f8f42458d.png) | ![image](https://user-images.githubusercontent.com/58642949/213840937-157bcd71-f599-4916-bbd3-91809dcf21bf.png) |

2023-01-21 03:19 UTC, franclobo commented on style.css
> +  }
- [ ] Kindly fix the size of this section to be similar to the Figma template. 👇🏽 

| Figma template | Your template |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/213841047-49a66586-c5ed-4362-b1c8-bbc91756cc23.png) | ![image](https://user-images.githubusercontent.com/58642949/213841068-d4921eec-a393-4928-ac62-0ccd93957649.png) |

2023-01-21 09:43 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @chawkimbarki  
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 09:43 UTC, iambenkis commented on index.html
> +                <p id="headline-text" class="secondary-text">Hello! My name is Chawki, a Full-Stack Software Developer who graduated from Microverse; an online training school that uses pair programm
> * [ ]  As requested b the previous code reviewer :recycle: , you should align this paragraph and the button in the  left  to stck to the Figma design , kindly fix it to be similar to the Figma template 👇🏽. See this as a aclient need to be meet ! :smile: 
 
|  Figma template   |    Your design |
| :---: | :---: |
| ![image](https://user-images.githubusercontent.com/58642949/213840922-bab339ff-6c86-4c55-91d1-f60f8f42458d.png)  |  ![image](https://user-images.githubusercontent.com/58642949/213840937-157bcd71-f599-4916-bbd3-91809dcf21bf.png) |

2023-01-21 10:36 UTC, AlphaNtihinduka requested changes
## Hi @chawkimbarki 🙋‍♂️

Good job working on your desktop. You have done the design to the best expectation and incredibly well. 👏  

However, there are some issues mostly with the headline.
You still need to implement a few on the project but you are almost there!!! :watch: 

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required Changes ♻️ 
- Kindly refer to the inline comments and apply the changes requested to have a final professional project.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-01-21 10:36 UTC, AlphaNtihinduka commented on index.html
> +        <ul>
- [ ] Kindly ensure that the hamburger does not display in the desktop version. Kindly follow the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#project-requirements) to implement this 👍 .

Your design 😎 
![humberger](https://user-images.githubusercontent.com/99394374/213863153-6781475f-e8b1-4625-b197-aee85ba128db.PNG)

2023-01-21 10:36 UTC, AlphaNtihinduka commented on index.html
> +            <li><a href="#">Contact</a></li>
- [ ] You have done great work by implementing the header 👍  👏 . However, the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#project-requirements) request to display items in the center.

2023-01-21 10:36 UTC, AlphaNtihinduka commented on index.html
> +                <p id="headline-text" class="secondary-text">Hello! My name is Chawki, a Full-Stack Software Developer who graduated from Microverse; an online training school that uses pair programm
- [ ] As the previous reviewers suggested, Kindly stick to the Figma design and project requirements. Please, ensure that the text is aligned to the left but it doesn't pass the middle of the page and there's a logo at the right. There's a Start collaboration button after the text.

Your design 😎 
![coll head](https://user-images.githubusercontent.com/99394374/213863119-5ed34679-26e9-418a-97a4-76de1bee3482.PNG)

2023-01-21 10:36 UTC, AlphaNtihinduka commented on index.html
> +            </div>
- [ ] [OPTIONAL] Kindly ensure that the `<img>` tag has `alt` text ☺️ . This is because it is read aloud to users by screen reader software, and it is indexed by search engines. It also displays on the page if the image fails to load, as in this example of a missing image.

2023-01-21 10:43 UTC, chawkimbarki commented
Hey @AlphaNtihinduka 
Thanks for the good review, but I think you are viewing the website on mobile screen size 😅, try changing it to 1440 x 900

2023-01-21 10:50 UTC, AlphaNtihinduka commented
> Hey @AlphaNtihinduka Thanks for the good review, but I think you are viewing the website on mobile screen size 😅, try changing it to 1440 x 900

Dear @chawkimbarki I have tried to recheck and confirm. I am seeing the same results. Can we please have a call and show me your version?

2023-01-21 10:52 UTC, chawkimbarki commented
@AlphaNtihinduka Sure
here is the zoom meeting link : https://microverse.zoom.us/j/92251862142?pwd=UEt6QXBpZWo0K0x6OVVsSXRHYWtGZz09
and here is the passcode : 259736

2023-01-23 12:16 UTC, sinansevgi requested changes
Hi @chawkimbarki , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] I noticed that the media query for the desktop version of the website is currently set at 1440px, however, [the project requirements ](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md)specify that the breakpoint should be at 768px. It's important that we ensure the website is built according to the specified requirements, so I recommend updating the media query to reflect the correct breakpoint.
![Screenshot 2023-01-23 at 14-58-06 curriculum-html-css_4_desktop_version md at main · microverseinc_curriculum-html-css](https://user-images.githubusercontent.com/1642014/214037355-cc65611b-3733-4605-924b-b65cace2f73c.png)

Happy Hacking! :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
Sinan Sevgi

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-23 17:38 UTC, mckent05 requested changes
Hi @chawkimbarki, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Your project looks good 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-23 17:38 UTC, mckent05 commented on style.css
> +  }
- You have done an excellent job so far, but please ensure that your navbar looks exactly like the Figma design template. I suggest removing the box shadow. Also please ensure that your nav links are centered in the middle Please fix this 🙏 
Your project:
<img width="950" alt="tjestjtj" src="https://user-images.githubusercontent.com/73607512/214107823-59d19a1d-18dd-4af7-ac10-cdbc073052b3.PNG">

Figma design:
<img width="541" alt="tbrtbrt" src="https://user-images.githubusercontent.com/73607512/214108018-e5690b4b-ae3b-4680-9056-685af1a6d068.PNG">

2023-01-23 17:38 UTC, mckent05 commented on index.html
> +
- This section of your portfolio isn't the same as the Figma template, PLease fix this 🙏 
Figma template:
- I can't find this section on your page. Please fix this 🙏 
<img width="539" alt="hwergrg" src="https://user-images.githubusercontent.com/73607512/214109347-7785e975-898b-4853-bb30-449fedb9c406.PNG">

Your project:
<img width="949" alt="nynynyey" src="https://user-images.githubusercontent.com/73607512/214109742-17ce18c7-a697-45c7-a37e-9800a0daae39.PNG">

2023-01-23 18:56 UTC, chawkimbarki commented on index.html
> +
hey @mckent05 
thanks for the good review, but none of the previous reviewers mentioned that and I only have a few hours to submit this project, also the projects section is there 👀.
anyways, if you are asking about the information of the project that is supposed to appear when you hover over it, that can only be implemented using JS or maybe some other techniques that I didn't learn at Microverse yet.
I only know HTML / CSS please I can't handle any more obstacles.

2023-01-23 19:01 UTC, chawkimbarki commented on index.html
> +
@mckent05  the only thing that was missing in my project is to make it for screens with a 768px width minimum and I did that.

2023-01-23 19:25 UTC, mckent05 commented on index.html
> +
Hello @chawkimbarki , I apologize for my mistake, I viewed your deployed page and suggested changes based on that, I am sorry about that, and I would correct my mistake as quickly as I can. Sorry for the inconveniences 🙏

2023-01-23 19:27 UTC, chawkimbarki commented on index.html
> +
@mckent05  Thank you so much ❤️
you are my savior.

2023-01-23 20:08 UTC, mckent05 commented on index.html
> +
Hello @chawkimbarki, I have made corrections to my reviews and made the second change optional since it requires the use of Javascript. Please submit your project for approval after making changes for the first suggested change 👍 👍

2023-01-23 20:27 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @chawkimbarki , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-23 20:43 UTC, merged